# SQL Querying

This notebook can be used to query tables in the SBA database. In order to use this notebook, you will need to set an environment variable 'SBA_DWH' to the database connection string. If you do not have the credentials, please slack us at #datasci-sba channel.

**It is best practice to not hard code database URI strings directly in notebooks or code as when we push to Github, that would mean credentials are public for anyone to see.**

In [1]:
import os

import pandas as pd
pd.options.display.max_columns = 999
import sqlalchemy as sqla
from sqlalchemy import create_engine

SBA_DWH = os.getenv('SBA_DWH')
engine = create_engine(SBA_DWH)

Below are the tables that currently exist in the database!

In [2]:
QUERY = """
select *
from information_schema.tables
where table_schema not in ('information_schema', 'pg_catalog', 'public')
"""
with engine.begin() as conn:
    results = pd.read_sql(QUERY, conn)
results.head(100)

,table_catalog,table_schema,table_name,table_type,self_referencing_column_name,reference_generation,user_defined_type_catalog,user_defined_type_schema,user_defined_type_name,is_insertable_into,is_typed,commit_action
0,postgres,data_ingest,irs_zip_data,BASE TABLE,None,None,None,None,None,YES,NO,None
1,postgres,data_ingest,sba__foia_7a_2010_present,BASE TABLE,None,None,None,None,None,YES,NO,None
2,postgres,data_ingest,census__zip_business_patterns,BASE TABLE,None,None,None,None,None,YES,NO,None
3,postgres,data_ingest,sba__foia_7a_1991_1999,BASE TABLE,None,None,None,None,None,YES,NO,None
4,postgres,data_ingest,sba__foia_7a_2000_2009,BASE TABLE,None,None,None,None,None,YES,NO,None
5,postgres,stg_analytics,sba_sfdo,BASE TABLE,None,None,None,None,None,YES,NO,None
6,postgres,stg_analytics,census_naics,BASE TABLE,None,None,None,None,None,YES,NO,None
7,postgres,stg_analytics,irs_income,BASE TABLE,None,None,None,None,None,YES,NO,None
8,postgres,trg_analytics,sba_zip_level,BASE TABLE,None,None,None,None,None,YES,NO,None
9,postgres,data_ingest,sba__foia_504_1991_present,BASE TABLE,None,None,None,None,None,YES,NO,None

## Edit your own query here!

In [4]:
QUERY = """
select
  program::text as program,
  BorrName,
  BorrStreet,
  BorrCity,
  BorrState,
  BorrZip,
  GrossApproval,
  ApprovalDate,
  ApprovalFiscalYear,
  FirstDisbursementDate,
  DeliveryMethod,
  subpgmdesc,
  InitialInterestRate,
  TermInMonths,
  NaicsCode,
  NaicsDescription,
  FranchiseCode,
  FranchiseName,
  ProjectCounty,
  ProjectState,
  SBADistrictOffice,
  CongressionalDistrict,
  BusinessType,
  LoanStatus,
  ChargeOffDate,
  GrossChargeOffAmount,
  JobsSupported,
  CDC_Name,
  CDC_Street,
  CDC_City,
  CDC_State,
  CDC_Zip,
  ThirdPartyLender_Name,
  ThirdPartyLender_City,
  ThirdPartyLender_State,
  ThirdPartyDollars,
  null as BankName,
  null as BankStreet,
  null as BankCity,
  null as BankState,
  null as BankZip,
  null as SBAGuaranteedApproval,
  null as RevolverStatus

from data_ingest.sba__foia_504_1991_present
limit 10
"""
with engine.begin() as conn:
    results = pd.read_sql(QUERY, conn)
results.head(100)

ProgrammingError: (psycopg2.ProgrammingError) column "program" does not exist
LINE 3:   program::text as program,
          ^
HINT:  Perhaps you meant to reference the column "sba__foia_504_1991_present.Program".
 [SQL: '\nselect\n  program::text as program,\n  BorrName,\n  BorrStreet,\n  BorrCity,\n  BorrState,\n  BorrZip,\n  GrossApproval,\n  ApprovalDate,\n  ApprovalFiscalYear,\n  FirstDisbursementDate,\n  DeliveryMethod,\n  subpgmdesc,\n  InitialInterestRate,\n  TermInMonths,\n  NaicsCode,\n  NaicsDescription,\n  FranchiseCode,\n  FranchiseName,\n  ProjectCounty,\n  ProjectState,\n  SBADistrictOffice,\n  CongressionalDistrict,\n  BusinessType,\n  LoanStatus,\n  ChargeOffDate,\n  GrossChargeOffAmount,\n  JobsSupported,\n  CDC_Name,\n  CDC_Street,\n  CDC_City,\n  CDC_State,\n  CDC_Zip,\n  ThirdPartyLender_Name,\n  ThirdPartyLender_City,\n  ThirdPartyLender_State,\n  ThirdPartyDollars,\n  null as BankName,\n  null as BankStreet,\n  null as BankCity,\n  null as BankState,\n  null as BankZip,\n  null as SBAGuaranteedApproval,\n  null as RevolverStatus\n\nfrom data_ingest.sba__foia_504_1991_present\nlimit 10\n']